-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Layouts

-- -----------------------------------------------------

hl.config({
	dwindle = {
		pseudotile = true,
		preserve_split = true,
	},
})

hl.config({
	master = {
		-- Commented out due to compatibility reasons
		-- new_status = master
	},
})

hl.config({
	gestures = {
		workspace_swipe = true,
		workspace_swipe_fingers = 3,
		workspace_swipe_distance = 500,
		workspace_swipe_invert = true,
		workspace_swipe_min_speed_to_force = 30,
		workspace_swipe_cancel_ratio = 0.5,
		workspace_swipe_create_new = true,
		workspace_swipe_forever = true,
	},
})

hl.config({
	binds = {
		workspace_back_and_forth = true,
		allow_workspace_cycles = true,
		pass_mouse_when_bound = false,
	},
})
