-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Window rules

-- -----------------------------------------------------

hl.window_rule({
	name = "tile_on",
	float = false,
	match = {
		title = "Microsoft-edge",
	},
})

hl.window_rule({
	name = "tile_on",
	float = false,
	match = {
		title = "^(Brave-browser)$",
	},
})

hl.window_rule({
	name = "tile_on",
	float = false,
	match = {
		title = "^(Chromium)$",
	},
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(pavucontrol)$",
	},
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(blueman-manager)$",
	},
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(nm-connection-editor)$",
	},
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(qalculate-gtk)$",
	},
	-- TODO: review rule: "float on"
})

-- Browser Picture in Picture

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(Picture-in-Picture)$",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		title = "^(Picture-in-Picture)$",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "move__69_5____4__",
	match = {
		title = "^(Picture-in-Picture)$",
	},
	move = "(69.5%) (4%)",
})

hl.window_rule({
	name = "idle_inhibit_always",
	idle_inhibit = "always",
	match = {
		class = "([window])",
	},
	-- TODO: review rule: "idle_inhibit always"
})

-- Available modes: none, always, focus, fullscreen

hl.layer_rule({
	match = {
		namespace = "waybar",
	},
	blur = true,
})

-- Pavucontrol floating

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(.*org.pulseaudio.pavucontrol.*)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__700___600_",
	match = {
		class = "(.*org.pulseaudio.pavucontrol.*)",
	},
	size = "(700) (600)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(.*org.pulseaudio.pavucontrol.*)",
	},
	center = true,
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(.*org.pulseaudio.pavucontrol.*)",
	},
	-- TODO: review rule: "pin on"
})

-- Waypaper

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(.*waypaper.*)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__900___700_",
	match = {
		class = "(.*waypaper.*)",
	},
	size = "(900) (700)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(.*waypaper.*)",
	},
	center = true,
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(.*waypaper.*)",
	},
	-- TODO: review rule: "pin on"
})

-- SwayNC

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	ignore_alpha = 0.5,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	ignore_alpha = 0.5,
})

-- ML4W Calendar floating

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(calendario)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "move__100_-w-16___66",
	match = {
		class = "(calendario)",
	},
	move = "(100%-w-16) (66)",
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(calendario)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "size__60____70__",
	match = {
		class = "(calendario)",
	},
	size = "(60%) (70%)",
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		initial_title = "(calendario)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "move__100_-w-16___66",
	match = {
		initial_title = "(calendario)",
	},
	move = "(100%-w-16) (66)",
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		initial_title = "(calendario)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "size__60____70__",
	match = {
		initial_title = "(calendario)",
	},
	size = "(60%) (70%)",
})

-- ML4W Sidebar floating

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(com.ml4w.sidebar)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "move__100_-w-16___66",
	match = {
		class = "(com.ml4w.sidebar)",
	},
	move = "(100%-w-16) (66)",
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(com.ml4w.sidebar)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "size__400___740_",
	match = {
		class = "(com.ml4w.sidebar)",
	},
	size = "(400) (740)",
})

-- Blueman Manager

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(blueman-manager)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__800___600_",
	match = {
		class = "(blueman-manager)",
	},
	size = "(800) (600)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(blueman-manager)",
	},
	center = true,
})

-- nwg-look

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(nwg-look)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__700___600_",
	match = {
		class = "(nwg-look)",
	},
	size = "(700) (600)",
})

hl.window_rule({
	name = "move__10____20__",
	match = {
		class = "(nwg-look)",
	},
	move = "(10%) (20%)",
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(nwg-look)",
	},
	-- TODO: review rule: "pin on"
})

-- nwg-displays

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(nwg-displays)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__900___600_",
	match = {
		class = "(nwg-displays)",
	},
	size = "(900) (600)",
})

hl.window_rule({
	name = "move__10____20__",
	match = {
		class = "(nwg-displays)",
	},
	move = "(10%) (20%)",
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(nwg-displays)",
	},
	-- TODO: review rule: "pin on"
})

-- System Mission Center

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(io.missioncenter.MissionCenter)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(io.missioncenter.MissionCenter)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(io.missioncenter.MissionCenter)",
	},
	center = true,
})

hl.window_rule({
	name = "size__900___600_",
	match = {
		class = "(io.missioncenter.MissionCenter)",
	},
	size = "(900) (600)",
})

-- System Mission Center Preference Window

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		title = "^(Preferences)$",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		title = "^(Preferences)$",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "center_on",
	match = {
		title = "^(Preferences)$",
	},
	center = true,
})

-- Gnome Calculator

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(org.gnome.Calculator)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__700___600_",
	match = {
		class = "(org.gnome.Calculator)",
	},
	size = "(700) (600)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(org.gnome.Calculator)",
	},
	center = true,
})

-- General floating

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(dotfiles-floating)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__1000___700_",
	match = {
		class = "(dotfiles-floating)",
	},
	size = "(1000) (700)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(dotfiles-floating)",
	},
	center = true,
})

-- Floating for Ghostty

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(ml4w.dotfiles.floating)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__1000___700_",
	match = {
		class = "(ml4w.dotfiles.floating)",
	},
	size = "(1000) (700)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(ml4w.dotfiles.floating)",
	},
	center = true,
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(ml4w.dotfiles.floating)",
	},
	-- TODO: review rule: "pin on"
})

-- XDG Desktop Portal

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- QT

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- GDK

hl.env("GDK_SCALE", 1)

-- Toolkit Backend

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("CLUTTER_BACKEND", "wayland")

-- Mozilla

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- Set the cursor size for xcursor

hl.env("XCURSOR_SIZE", 24)

-- Ozone

hl.env("OZONE_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- Dotfiles Sidepad

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "(dotfiles-sidepad)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__85____70__",
	match = {
		class = "(dotfiles-sidepad)",
	},
	size = "(85%) (70%)",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "(dotfiles-sidepad)",
	},
	center = true,
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		class = "(dotfiles-sidepad)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		initial_title = "(dotfiles-sidepad)",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size__85____70__",
	match = {
		initial_title = "(dotfiles-sidepad)",
	},
	size = "(85%) (70%)",
})

hl.window_rule({
	name = "center_on",
	match = {
		initial_title = "(dotfiles-sidepad)",
	},
	center = true,
})

hl.window_rule({
	name = "pin_on",
	pin = true,
	match = {
		initial_title = "(dotfiles-sidepad)",
	},
	-- TODO: review rule: "pin on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "org.gnome.Nautilus",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "org.telegram.desktop",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "org.gnome.TextEditor",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "org.kde.kdeconnect.app",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "localsend",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "vesktop",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "Spotify",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "heroic",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "modrinth-app",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "com.usebottles.bottles",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "float_on",
	float = true,
	match = {
		class = "com.rafaelmardojai.Blanket",
	},
	-- TODO: review rule: "float on"
})
