cursor-color = #dfe4dc
foreground = #dfe4dc
background = #101510
selection-foreground = #223527
selection-background = #b6ccb9
palette = 0=#383839
palette = 1=#30403B
palette = 2=#41584F
palette = 3=#527063
palette = 4=#628878
palette = 5=#73A08C
palette = 6=#73A08C
palette = 7=#B1C7BD
palette = 8=#7C8B84
palette = 9=#30403B
palette = 10=#41584F
palette = 11=#527063
palette = 12=#628878
palette = 13=#73A08C
palette = 14=#73A08C
palette = 15=#B1C7BD
