-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- General workspace rules

-- name: "Default"

-- -----------------------------------------------------

-- Assigning workspace to a certain monitor. Below are just examples

for i = 1, 10 do
    hl.workspace_rule({
        workspace = tostring(i),
        persistent = true,
    })
end

hl.workspace_rule({
    workspace = 1,
    layout = "master",
    persistent = true,
})

hl.workspace_rule({
    workspace = 2,
    layout = "scrolling",
    persistent = true,
})

hl.workspace_rule({
    workspace = 3,
    layout = "dwindle",
    persistent = true,
})

hl.window_rule({
    match = {
        workspace = "5",
    },
    float = true,
})

-- workspace = 5, monitor:DP-2

-- workspace = 6, monitor:DP-2

-- workspace = 7, monitor:DP-2

-- workspace = 8, monitor:DP-2

-- Example rules (from https://wiki.hyprland.org/Configuring/Workspace-Rules/)

-- workspace = 3, rounding:false, decorate:false

-- workspace = name:coding, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-1

-- workspace = 8,bordersize:8

-- workspace = name:Hello, monitor:DP-1, default:true

-- workspace = name:gaming, monitor:desc:Chimei Innolux Corporation 0x150C, default:true

-- workspace = 5, on-created-empty:[float] firefox

-- workspace = special:scratchpad, on-created-empty:foot
