color0       #000004
color8       #849393
color1       #4E6068
color9       #4E6068
color2       #5D767C
color10      #5D767C
color3       #6C8C90
color11      #6C8C90
color4       #7CA1A3
color12      #7CA1A3
color5       #8BB7B7
color13      #8BB7B7
color6       #8BB7B7
color14      #8BB7B7
color7       #BCD3D3
color15      #BCD3D3