color0       #000300
color1       #1F3B17
color2       #1F3B17
color3       #02AAE6
color4       #FB8B71
color5       #73C62D
color6       #79CF2E
color7       #B4DF8E
color8       #7E9C63
color9       #1F3B17
color10      #1F3B17
color11      #02AAE6
color12      #FB8B71
color13      #73C62D
color14      #79CF2E
color15      #B4DF8E
