color0       #0D0000
color8       #AC855D
color1       #8A4B1C
color9       #8A4B1C
color2       #A75C1C
color10      #A75C1C
color3       #C46D1C
color11      #C46D1C
color4       #E07E1D
color12      #E07E1D
color5       #FD8F1D
color13      #FD8F1D
color6       #FD8F1D
color14      #FD8F1D
color7       #F6BF86
color15      #F6BF86