
#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
# font_family                 JetBrainsMono Nerd Font
font_size                   12
# bold_font                   auto
# italic_font                 auto
# bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
cursor_shape                underline
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge top
tab_bar_align right
map ctrl+shift+] next_tab
active_tab_background #FFA036
inactive_tab_background #463F42
tab_bar_font_size 0.5
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
map ctrl+shift+[ previous_tab
map ctrl+tab no_op
map ctrl+shift+tab no_op
tab_title_template ""
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
background_opacity          0.70
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

# Animated cursor follows text
cursor_trail 2

# Include wallpaper colors
include colors-wallust.conf
include colors-matugen.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration

# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
