theme = "dexmachina.toml"

[panel]
padding = [5, 1]

confirm-before-quit = false

[cursor]
blinking = true
blinking-interval = 500

[editor]
program = "nvim"
args = []

[window]
decorations = "enabled"
blur=true
opacity = 0.87

[keyboard]
use-kitty-keyboard-protocol = true

[bell]
visual = false
audio = false

[fonts]
family = "Maple Mono NF CN"
size = 16.2
use-drawable-chars = true

[effects]
trail-cursor = true

[shell]
program = "/bin/zsh"
