theme = "dexmachina.toml"

padding-x = 10
padding-y = [10, 1]

confirm-before-quit = false

[cursor]
shape = 'block'
blinking = true
blinking-interval = 500

[editor]
program = "nvim"
args = []

[window]
opacity = 0.85

[keyboard]
use-kitty-keyboard-protocol = true

[bell]
visual = false
audio = true

[fonts]
family = "Maple Mono NF CN"
size = 16
use-drawable-chars = true

[fonts.regular]
style = "Normal"
weight = 650

[fonts.bold]
style = "Normal"
weight = 900

[fonts.italic]
style = "Italic"
weight = 650

[fonts.bold-italic]
style = "Italic"
weight = 900

[shell]
program = "/bin/zsh"

[bindings]
keys = [
  { key = "l", with = "control | shift", esc = "\u001b[2J\u001b[H" },
#  { key = "q", with = "super", action = "Quit" },
  { key = "l", with = "control", esc = "^Wl" }
]

