backend = "resized"
threshold = 22
colorspace = "lab"
contrast = true
palette = "dark"

[templates]
kitty.template = 'kitty-colors.conf'
kitty.target = '~/.config/kitty/colors-wallust.conf'

starship.template = 'paleta.toml'
starship.target = '~/.config/starship.toml'

#ghostty.template = 'ghostty'
#ghostty.target = '~/.cache/wallust/ghostty.conf'

rio.template = 'rio'
rio.target = '~/.config/rio/cache/colors_wallust.toml'
