version = 3
patch_pwsh_bleed = true
final_space = true

[palette]
  color0 = '#1a110f'
  color1 = ''
  color10 = '#ffb59d'
  color11 = ''
  color12 = ''
  color13 = '#390c00'
  color14 = ''
  color15 = '#f1dfda'
  color2 = ''
  color3 = ''
  color4 = ''
  color5 = ''
  color6 = ''
  color7 = ''
  color8 = ''
  color9 = ''

[transient_prompt]
  template = '  ❯❯ {{ .AbsolutePWD }} : '
  foreground = 'p:color15'
  background = 'transparent'
  newline = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = "\n╭─"
    foreground = 'p:color15'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{ .UserName }}'
    foreground = 'p:color15'
    background = 'p:color13'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '󱐋'
    foreground = '#ff5555'
    powerline_symbol = ''
    background = 'p:color13'
    type = 'root'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Icon }}  '
    foreground = 'p:color15'
    powerline_symbol = ''
    background = 'p:color13'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' 󰉖 {{ path .Path .Location }}'
    foreground = 'p:color13'
    background = 'p:color10'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' ({{ url .UpstreamIcon .UpstreamURL }} {{ url .HEAD .UpstreamURL }}){{ if gt .Ahead 0 }}<#50fa7b> +{{ .Ahead }}</>{{ end }}{{ if gt .Behind 0 }}<#ff5555> -{{ .Behind }}</>{{ end }}{{ if .Working.Changed }}<p:color15>  {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }}<p:color15>  {{ .Staging.String }}</>{{ end }}'
    foreground = 'p:color13'
    background = '#ffb86c'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      display_changing_color = true
      fetch_status = true
      fetch_upstream_icon = true
      full_branch_path = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:color13'
    background = '#50fa7b'
    type = 'node'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:color13'
    background = '#ff5555'
    type = 'npm'
    style = 'diamond'

    [blocks.segments.properties]
      display_mode = 'files'
      extensions = ['package-lock.json']

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '󰋁 {{ .Full }}'
    foreground = 'p:color13'
    background = '#ffb86c'
    type = 'pnpm'
    style = 'diamond'

    [blocks.segments.properties]
      display_mode = 'files'
      extensions = ['pnpm-lock.yaml']

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:color13'
    background = '#50fa7b'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      display_mode = 'files'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:color13'
    background = '#ff79c6'
    type = 'java'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:color15'
    background = '#6272a4'
    type = 'php'
    style = 'diamond'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰>->'
    foreground = 'p:color15'
    type = 'text'
    style = 'diamond'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
