-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Key bindings

-- name: "Default"

-- -----------------------------------------------------

-- SUPER KEY

local mainMod = "SUPER"

local HYPRSCRIPTS = "~/.config/hypr/scripts"

local SCRIPTS = "~/.config/ml4w/scripts"

local DEXCRIPTS = "~/.config/hypr/dexcripts"

-- Applications

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

-- Open the terminal

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("~/.config/ml4w/settings/browser.sh"))

-- Open the browser

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("~/.config/ml4w/settings/filemanager.sh"))

-- Open the filemanager

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "E", hl.dsp.exec_cmd("~/.config/ml4w/settings/emojipicker.sh"))

-- Open the emoji picker

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "C", hl.dsp.exec_cmd("~/.config/ml4w/settings/calculator.sh"))

-- Open the calculator

-- Windows

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

-- Kill active window

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "Q",
	hl.dsp.exec_cmd("hyprctl activewindow| grep pid| tr -d 'pid:'| xargs kill")
)

-- Quit active window and all open instances

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Set active window to fullscreen

hl.bind(mainMod .. " + " .. "M", hl.dsp.window.fullscreen())

-- Maximize Window

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())

-- Toggle active windows into floating mode

hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))

-- Toggle all windows into floating mode

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- Move window with the mouse

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize window with the mouse

hl.bind(mainMod .. " + SHIFT + right", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 100 0"))

-- Increase window width with keyboard

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -100 0"))

-- Reduce window width with keyboard

hl.bind(mainMod .. " + SHIFT + down", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 100"))

-- Increase window height with keyboard

hl.bind(mainMod .. " + SHIFT + up", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -100"))

-- Reduce window height with keyboard

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

-- Toggle window group

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "left", hl.dsp.window.swap({ direction = "left" }))

-- Swap tiled window left

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "right", hl.dsp.window.swap({ direction = "right" }))

-- Swap tiled window right

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "up", hl.dsp.window.swap({ direction = "up" }))

-- Swap tiled window up

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "down", hl.dsp.window.swap({ direction = "down" }))

-- Swap tiled window down

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.cycle_next())

-- Actions

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

-- Reload Hyprland configuration

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-animations.sh"))

-- Toggle animations

hl.bind("PRINT", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"))

-- Take a screenshot

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"))

-- Take a screenshot

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Q", hl.dsp.exec_cmd("~/.config/ml4w/scripts/wlogout.sh"))

-- Start wlogout

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("waypaper --random"))

-- Change the wallpaper

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "W", hl.dsp.exec_cmd("waypaper"))

-- Open wallpaper selector

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-automation.sh"))

-- Start random wallpaper script

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "RETURN", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -replace -i"))

-- Open application launcher

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.exec_cmd("~/.config/hypr/scripts/keybindings.sh"))

-- Show keybindings

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("~/.config/waybar/launch.sh"))

-- Reload waybar

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd("~/.config/waybar/toggle.sh"))

-- Toggle waybar

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "B", hl.dsp.exec_cmd("~/.config/nwg-dock-hyprland/toggle.sh"))

-- Toggle nwg-dock

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("~/.config/hypr/scripts/loadconfig.sh"))

-- Reload hyprland config

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("~/.config/ml4w/scripts/cliphist.sh"))

-- Open clipboard manager

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "T", hl.dsp.exec_cmd("~/.config/waybar/themeswitcher.sh"))

-- Open waybar theme switcher

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprshade.sh"))

-- Toggle screenshader

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "G", hl.dsp.exec_cmd("~/.config/hypr/scripts/gamemode.sh"))

-- Toggle game mode

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.exec_cmd("~/.config/hypr/scripts/power.sh lock"))

-- Start wlogout

-- Sidepad

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.exec_cmd("~/.config/ml4w/scripts/sidepad.sh"))

-- Open Sidepad

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.exec_cmd("~/.config/ml4w/scripts/sidepad.sh --hide"))

-- Close Sidepad

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("kitty --title dotfiles-sidepad"))

-- Init Sidepad

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "S", hl.dsp.exec_cmd("~/.config/ml4w/scripts/sidepad.sh --select"))

-- Workspaces

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

-- Open workspace 1

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

-- Open workspace 2

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

-- Open workspace 3

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

-- Open workspace 4

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

-- Open workspace 5

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

-- Open workspace 6

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

-- Open workspace 7

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

-- Open workspace 8

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- Open workspace 9

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Open workspace 10

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

-- Move active window to workspace 1

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

-- Move active window to workspace 2

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

-- Move active window to workspace 3

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

-- Move active window to workspace 4

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- Move active window to workspace 5

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

-- Move active window to workspace 6

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

-- Move active window to workspace 7

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

-- Move active window to workspace 8

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- Move active window to workspace 9

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Move active window to workspace 10

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "m+1" }))

-- Open next workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "m-1" }))

-- Open previous workspace

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 1"))

-- Move all windows to workspace 1

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 2"))

-- Move all windows to workspace 2

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 3"))

-- Move all windows to workspace 3

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 4"))

-- Move all windows to workspace 4

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 5"))

-- Move all windows to workspace 5

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 6"))

-- Move all windows to workspace 6

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 7"))

-- Move all windows to workspace 7

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 8"))

-- Move all windows to workspace 8

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 9"))

-- Move all windows to workspace 9

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 10"))

-- Move all windows to workspace 10

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

-- Open next workspace

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Open previous workspace

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.focus({ workspace = "empty" }))

-- Open the next empty workspace

-- Fn keys

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -q s +5%"))

-- Increase brightness by 5%

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -q s 5%-"))

-- Reduce brightness by 5%

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ +5%")
)

-- Increase volume by 5%

hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ -5%")
)

-- Reduce volume by 5%

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

-- Toggle mute

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

-- Audio play pause

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))

-- Audio pause

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

-- Audio next

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Audio previous

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))

-- Toggle microphone

hl.bind("XF86Calculator", hl.dsp.exec_cmd("~/.config/ml4w/settings/calculator.sh"))

-- Open calculator

-- hl.bind("XF86Lock", hl.dsp.exec_cmd("hyprlock"))

-- Open screenlock

hl.bind("XF86Tools", hl.dsp.exec_cmd("flatpak run com.ml4w.settings"))

-- Open ML4W Dotfiles Settings app

hl.bind("code:238", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s +10"))

hl.bind("code:237", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s 10-"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("hyprctl eval \"hl.config({ general = { layout = 'dwindle' } })\""))

-- Modo DWINDLE (tiling normal, golden ratio)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "M", hl.dsp.exec_cmd("hyprctl eval \"hl.config({ general = { layout = 'master' } })\""))

--Work mode

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("hyprctl eval \"hl.config({ general = { layout = 'scrolling' } })\""))

--Scroller mode

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

--pseudo

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("rofi-rbw"))

--password manager

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.layout("move -col"))

-- Foca pra esquerda

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.layout("move +col"))

-- Foca pra direita

-- Move janela atual

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprctl dispatch movewindow r"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.exec_cmd("hyprctl dispatch movewindow l"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "N", hl.dsp.exec_cmd("~/.config/hypr/dexcripts/nvim.sh"))

-- Abre o kitty com nvim

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "D", hl.dsp.exec_cmd("kitty -e nvim ~/GDrive/rpg/Diario/"))

-- Abrir diário

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "P", hl.dsp.exec_cmd("kitty -e poketex"))

--Pokedex

-- Zoom

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Z", function()
	local cur = tonumber(hl.get_config("cursor:zoom_factor")) or 1.0
	hl.config({ cursor = { zoom_factor = cur + 0.5 } })
end)

-- Increase display zoom

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Z", function()
	local cur = tonumber(hl.get_config("cursor:zoom_factor")) or 1.0
	if cur > 1.0 then
		hl.config({ cursor = { zoom_factor = math.max(1.0, cur - 0.5) } })
	end
end)

-- Decrease display zoom

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "Z", function()
	hl.config({ cursor = { zoom_factor = 1.0 } })
end)

-- Reset display zoom

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("kitty --title dotfiles-sidepad -e aurroamer -f"))

hl.bind("ALT" .. " + " .. "up", hl.dsp.exec_cmd("~/.config/hypr/dexcripts/rotate-up.sh"))

hl.bind("ALT" .. " + " .. "right", hl.dsp.exec_cmd("~/.config/hypr/dexcripts/rotate-right.sh"))

hl.bind("ALT" .. " + " .. "down", hl.dsp.exec_cmd("~/.config/hypr/dexcripts/rotate-down.sh"))

hl.bind("ALT" .. " + " .. "left", hl.dsp.exec_cmd("~/.config/hypr/dexcripts/rotate-left.sh"))
