-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--    ___       __           __           __
--   / _ |__ __/ /____  ___ / /____ _____/ /_
--  / __ / // / __/ _ \(_-</ __/ _ `/ __/ __/
-- /_/ |_\_,_/\__/\___/___/\__/\_,_/_/  \__/

--

-- Setup XDG for screen sharing and start waypaper and waybar

-- Start Polkit

-- Load Wallpaper

-- Load Notification Daemon

-- Load GTK settings

-- Using hypridle to start hyprlock

-- Load cliphist history

-- Autostart ML4W App

-- Start autostart cleanup

-- Load configuration from ML4W Hyprland Settings App

-- Dock

-- Setup plugins

-- Envs

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("~/.config/hypr/scripts/xdg.sh")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("~/.config/hypr/scripts/wallpaper-restore.sh")
	hl.exec_cmd("swaync")
	hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("~/.config/ml4w/scripts/ml4w-autostart.sh")
	hl.exec_cmd("~/.config/hypr/scripts/cleanup.sh")
	hl.exec_cmd("~/.config/nwg-dock-hyprland/launch.sh")
	hl.exec_cmd("mkdir -p /run/user/$(id -u)/hyprpm && chmod 700 /run/user/$(id -u)/hyprpm")
	hl.exec_cmd("hyprpm reload")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("awww-daemon &")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd("~/.config/com.ml4w.hyprlandsettings/hyprctl.sh")
end)
