-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Add your additional Hyprland configurations here

--

-- This is an additional key binding

-- bind = $mainMod CTRL, up, workspace, empty

--

-- Example for xwayland

-- xwayland {

--   force_zero_scaling = true

-- }

-- qt5ct environment variable

-- env = QT_QPA_PLATFORMTHEME,qt5ct

-- SDL version

hl.env("SDL_VIDEODRIVER", "wayland")

-- env = SDL_VIDEODRIVER,x11

-- No Hardware Cursor

-- cursor {

--     no_hardware_cursors = false

-- }

-- Blur for waybar

hl.layer_rule({
	match = {
		namespace = "match:namespace . *waybar.*",
	},
	blur = 1,
})

hl.layer_rule({
	match = {
		namespace = "match:namespace . *waybar.*",
	},
	ignore_alpha = 0.0,
})
