-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Keyboard Layout

-- https://wiki.hyprland.org/Configuring/Variables/#input

-- -----------------------------------------------------

hl.config({
	input = {
		kb_layout = "us,br",
		kb_variant = "intl,abnt2",
		-- kb_model = thinkpad
		kb_options = "grp:ctrl_space_toggle",
		numlock_by_default = true,
		mouse_refocus = false,
		repeat_delay = 300,
		repeat_rate = 40,
		accel_profile = "flat",
		follow_mouse = 1,
		touchpad = {
			-- for desktop
			natural_scroll = false,
			-- natural_scroll = yes
			middle_button_emulation = true,
			-- clickfinger_behavior = false
			scroll_factor = 1.0,
			-- Touchpad scroll factor
			disable_while_typing = false,
		},
		force_no_accel = true,
		sensitivity = 1.0,
		-- Pointer speed: -1.0 - 1.0, 0 means no modification.
	},
})

if hl.plugin and hl.plugin.hyprgrass then
	hl.config({
		plugin = {
			hyprgrass = {
				sensitivity = 4.0,
				edge_margin = 30,
			},
		},
	})

	hl.plugin.hyprgrass.bind({
		pattern = { kind = "edge", origin = "r", direction = "l" },
		action = hl.dsp.exec_cmd("hyprctl dispatch workspace +1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "edge", origin = "l", direction = "r" },
		action = hl.dsp.exec_cmd("hyprctl dispatch workspace -1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "edge", origin = "r", direction = "r" },
		action = hl.dsp.exec_cmd("hyprctl dispatch workspace -1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "edge", origin = "l", direction = "l" },
		action = hl.dsp.exec_cmd("hyprctl dispatch workspace +1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "swipe", fingers = 4, direction = "r" },
		action = hl.dsp.exec_cmd("hyprctl dispatch movetoworkspacesilent +1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "swipe", fingers = 4, direction = "l" },
		action = hl.dsp.exec_cmd("hyprctl dispatch movetoworkspacesilent -1"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "edge", origin = "l", direction = "d" },
		action = hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -4%"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "swipe", fingers = 4, direction = "d" },
		action = hl.dsp.exec_cmd("hyprctl dispatch killactive"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "swipe", fingers = 3, direction = "u" },
		action = hl.dsp.exec_cmd("hyprctl dispatch fullscreen"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "swipe", fingers = 3, direction = "d" },
		action = hl.dsp.exec_cmd("hyprctl dispatch togglefloating"),
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "longpress", fingers = 3 },
		action = hl.dsp.exec_cmd("hyprctl dispatch movewindow"),
		mouse = true,
	})
	hl.plugin.hyprgrass.bind({
		pattern = { kind = "longpress", fingers = 2 },
		action = hl.dsp.exec_cmd("hyprctl dispatch resizewindow"),
		mouse = true,
	})
end
