# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = us,br
    kb_variant = intl,abnt2
    # kb_model = thinkpad
    kb_options = grp:ctrl_space_toggle
    numlock_by_default = true
    mouse_refocus = false
    repeat_delay=300
    repeat_rate=40
    accel_profile="flat"

    follow_mouse = 1
    touchpad {
        # for desktop
        natural_scroll = false

        # natural_scroll = yes
         middle_button_emulation = true
        # clickfinger_behavior = false
        scroll_factor = 1.0  # Touchpad scroll factor
        disable_while_typing=false
    }
    force_no_accel=true

    sensitivity = 1.0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = br,us
  kb_variant = abnt2,intl
  }

gesture = 3, up, fullscreen
gesture = 3, down, float

plugin {
    touch_gestures {
        sensitivity = 4.0
        edge_margin = 30
        hyprgrass-bind = , edge:r:l, workspace, +1
        hyprgrass-bind = , edge:l:r, workspace, -1
        hyprgrass-bind = , edge:r:r, workspace, -1
        hyprgrass-bind = , edge:l:l, workspace, +1
        hyprgrass-bind = , swipe:4:r, exec, hyprctl dispatch movetoworkspacesilent +1
        hyprgrass-bind = , swipe:4:l, exec, hyprctl dispatch movetoworkspacesilent -1
        hyprgrass-bind = , edge:l:d, exec, pactl set-sink-volume @DEFAULT_SINK@ -4%
        hyprgrass-bind = , swipe:4:d, killactive
        hyprgrass-bind = , swipe:3:u, exec, hyprctl dispatch fullscreen
        hyprgrass-bind = , swipe:3:d, exec, hyprctl dispatch togglefloating
        hyprgrass-bind = , swipe:3:rd, exec, kitty --title "dotfiles-sidepad"
        hyprgrass-bindm = , longpress:3, movewindow
        hyprgrass-bindm = , longpress:2, resizewindow
    }
}
