# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = us,br
    kb_variant = intl,abnt2
    kb_model =
    kb_options = grp:ctrl_space_toggle
    numlock_by_default = true
    mouse_refocus = false
    repeat_delay=300
    repeat_rate=40

    follow_mouse = 1
    touchpad {
        # for desktop
        natural_scroll = false

        # natural_scroll = yes
         middle_button_emulation = true
        # clickfinger_behavior = false
        scroll_factor = 1.0  # Touchpad scroll factor
    }

    force_no_accel = true
    sensitivity = -1.0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = br,us
  kb_variant = abnt2,intl
  }
