creation_rules:
  - path_regex: (.*)?secrets.*\.yml$
    key_groups:
      - pgp:
          - 0DEE1E3B758249FCFC573913529E8F90A6D61355
        age:
          - age1mse4sc2kmk59plkka3swwcrslq2gf55s6ej2edx9tk5cx9gn5a7qq09qmk

  - path_regex: .*\.local/share/chaos/ramblings/.*\.yml$
    key_groups:
      - pgp:
          - 0DEE1E3B758249FCFC573913529E8F90A6D61355
        age:
          - age1mse4sc2kmk59plkka3swwcrslq2gf55s6ej2edx9tk5cx9gn5a7qq09qmk
