local M = {}

M.palettes = {
  harmony = {
    keyword = "#CAA5F7",
    function_ = "#FF70A2",
    string = "#93E1D4",
    type = "#FAB286",
    var = "#FBA6CD",
    number = "#9DCFF9",
    boolean = "#FF85B9",
    comment = "#9E8195",
    operator = "#F86EA7",
    constant = "#FFBEDD",
    param = "#E5A4C7",
    delimiter = "#9399B3",
    match_paren = "#F79E45",
    match_bg = "#3B2230",
    border = "#9DCFF9",
    title = "#FF8EBD",
    pmenu_sel = "#93E1D4",
    pmenu_sel_fg = "#101010",
    diag_err = "#FF4F88",
    diag_warn = "#F5E36C",
    diag_info = "#9DCFF9",
    diag_hint = "#93E1D4",
  },
  sakura = {
    keyword = "#DDB6F2",
    function_ = "#F4B8E4",
    string = "#A6D189",
    type = "#EA999C",
    var = "#F2CDCD",
    number = "#85C1DC",
    boolean = "#EEBEBE",
    comment = "#8C838E",
    operator = "#E78284",
    constant = "#F5C2E7",
    param = "#E5C890",
    delimiter = "#9399B3",
    match_paren = "#FFA066",
    match_bg = "#362734",
    border = "#85C1DC",
    title = "#F4B8E4",
    pmenu_sel = "#A6D189",
    pmenu_sel_fg = "#101010",
    diag_err = "#E78284",
    diag_warn = "#E5C890",
    diag_info = "#85C1DC",
    diag_hint = "#A6D189",
  },
  cyber = {
    keyword = "#D4A5FF",
    function_ = "#FF5CA0",
    string = "#7EE8D0",
    type = "#FFD180",
    var = "#FFC0E0",
    number = "#80D8FF",
    boolean = "#FF79B0",
    comment = "#827083",
    operator = "#FF80B5",
    constant = "#FFE082",
    param = "#EBB0D2",
    delimiter = "#9399B3",
    match_paren = "#FF9100",
    match_bg = "#421832",
    border = "#7EE8D0",
    title = "#FF5CA0",
    pmenu_sel = "#80D8FF",
    pmenu_sel_fg = "#050505",
    diag_err = "#FF3366",
    diag_warn = "#FFE082",
    diag_info = "#80D8FF",
    diag_hint = "#7EE8D0",
  },
  vaporwave = {
    keyword = "#B4BEFE",
    function_ = "#F38BA8",
    string = "#89DCEB",
    type = "#F9E2AF",
    var = "#F5C2E7",
    number = "#74C7EC",
    boolean = "#F5A97F",
    comment = "#7F849C",
    operator = "#CBA6F7",
    constant = "#FAB387",
    param = "#EBA0AC",
    delimiter = "#9399B3",
    match_paren = "#FAB387",
    match_bg = "#312338",
    border = "#89DCEB",
    title = "#F5C2E7",
    pmenu_sel = "#89DCEB",
    pmenu_sel_fg = "#101010",
    diag_err = "#F38BA8",
    diag_warn = "#F9E2AF",
    diag_info = "#89DCEB",
    diag_hint = "#A6E3A1",
  },
  lavender = {
    keyword = "#B4A1FF",
    function_ = "#F687B3",
    string = "#81E6D9",
    type = "#FBD38D",
    var = "#FBB6CE",
    number = "#90CDF4",
    boolean = "#FEB2B2",
    comment = "#7B6E85",
    operator = "#D6BCFA",
    constant = "#FED7E2",
    param = "#E9D8FD",
    delimiter = "#9399B3",
    match_paren = "#F6AD55",
    match_bg = "#30223A",
    border = "#B4A1FF",
    title = "#F687B3",
    pmenu_sel = "#81E6D9",
    pmenu_sel_fg = "#0E1817",
    diag_err = "#FC8181",
    diag_warn = "#F6E05E",
    diag_info = "#90CDF4",
    diag_hint = "#81E6D9",
  },
  matcha = {
    keyword = "#C6A0F6",
    function_ = "#F38BA8",
    string = "#A6D189",
    type = "#E5C890",
    var = "#F2CDCD",
    number = "#85C1DC",
    boolean = "#EA999C",
    comment = "#7C8578",
    operator = "#EA999C",
    constant = "#F5C2E7",
    param = "#E5C890",
    delimiter = "#9399B3",
    match_paren = "#FAB387",
    match_bg = "#352B28",
    border = "#A6D189",
    title = "#F38BA8",
    pmenu_sel = "#A6D189",
    pmenu_sel_fg = "#141C12",
    diag_err = "#E78284",
    diag_warn = "#E5C890",
    diag_info = "#85C1DC",
    diag_hint = "#A6D189",
  },
  cosmic = {
    keyword = "#D8B4FE",
    function_ = "#F472B6",
    string = "#67E8F9",
    type = "#FDE047",
    var = "#FBCFE8",
    number = "#93C5FD",
    boolean = "#FCA5A5",
    comment = "#7B768E",
    operator = "#C084FC",
    constant = "#FEF08A",
    param = "#E9D5FF",
    delimiter = "#9399B3",
    match_paren = "#FB923C",
    match_bg = "#2B213A",
    border = "#67E8F9",
    title = "#F472B6",
    pmenu_sel = "#67E8F9",
    pmenu_sel_fg = "#081E24",
    diag_err = "#F87171",
    diag_warn = "#FDE047",
    diag_info = "#67E8F9",
    diag_hint = "#A7F3D0",
  },
  nordic = {
    keyword = "#B48EAD",
    function_ = "#D08770",
    string = "#A3BE8C",
    type = "#EBCB8B",
    var = "#E5D4E8",
    number = "#88C0D0",
    boolean = "#BF616A",
    comment = "#6D7993",
    operator = "#B48EAD",
    constant = "#EBCB8B",
    param = "#D8DEE9",
    delimiter = "#9399B3",
    match_paren = "#D08770",
    match_bg = "#30262C",
    border = "#88C0D0",
    title = "#D08770",
    pmenu_sel = "#88C0D0",
    pmenu_sel_fg = "#0E1A1E",
    diag_err = "#BF616A",
    diag_warn = "#EBCB8B",
    diag_info = "#88C0D0",
    diag_hint = "#A3BE8C",
  },
  dracula = {
    keyword = "#BD93F9",
    function_ = "#FF6E96",
    string = "#7DF9A4",
    type = "#FFB86C",
    var = "#FF79C6",
    number = "#8BE9FD",
    boolean = "#FF5555",
    comment = "#6272A4",
    operator = "#FF79C6",
    constant = "#F1FA8C",
    param = "#E9D5FF",
    delimiter = "#9399B3",
    match_paren = "#FFB86C",
    match_bg = "#3B1C28",
    border = "#BD93F9",
    title = "#FF79C6",
    pmenu_sel = "#7DF9A4",
    pmenu_sel_fg = "#101010",
    diag_err = "#FF5555",
    diag_warn = "#FFB86C",
    diag_info = "#8BE9FD",
    diag_hint = "#7DF9A4",
  },
  boba = {
    keyword = "#D4A373",
    function_ = "#E76F51",
    string = "#A7C957",
    type = "#F4A261",
    var = "#E9D8A6",
    number = "#90E0EF",
    boolean = "#E29578",
    comment = "#8A7968",
    operator = "#DDA15E",
    constant = "#FAEDCD",
    param = "#DDB892",
    delimiter = "#9399B3",
    match_paren = "#F4A261",
    match_bg = "#3A2A20",
    border = "#F4A261",
    title = "#E76F51",
    pmenu_sel = "#A7C957",
    pmenu_sel_fg = "#1A2210",
    diag_err = "#E76F51",
    diag_warn = "#F4A261",
    diag_info = "#90E0EF",
    diag_hint = "#A7C957",
  },
  abyssal = {
    keyword = "#A855F7",
    function_ = "#EC4899",
    string = "#14B8A6",
    type = "#06B6D4",
    var = "#F472B6",
    number = "#60A5FA",
    boolean = "#FB7185",
    comment = "#64748B",
    operator = "#C084FC",
    constant = "#67E8F9",
    param = "#CBD5E1",
    delimiter = "#9399B3",
    match_paren = "#38BDF8",
    match_bg = "#1E2538",
    border = "#14B8A6",
    title = "#EC4899",
    pmenu_sel = "#14B8A6",
    pmenu_sel_fg = "#042F2E",
    diag_err = "#FB7185",
    diag_warn = "#38BDF8",
    diag_info = "#60A5FA",
    diag_hint = "#14B8A6",
  },
  mochi = {
    keyword = "#E09F3E",
    function_ = "#FF8FAB",
    string = "#80ED99",
    type = "#FB8500",
    var = "#FFC6FF",
    number = "#8ECAE6",
    boolean = "#FF5D8F",
    comment = "#837B85",
    operator = "#FF8FAB",
    constant = "#FFE5D9",
    param = "#FFCAD4",
    delimiter = "#9399B3",
    match_paren = "#FB8500",
    match_bg = "#3A2328",
    border = "#80ED99",
    title = "#FF8FAB",
    pmenu_sel = "#80ED99",
    pmenu_sel_fg = "#0D2B17",
    diag_err = "#FF5D8F",
    diag_warn = "#FB8500",
    diag_info = "#8ECAE6",
    diag_hint = "#80ED99",
  },
  sailor = {
    keyword = "#CDB4DB",
    function_ = "#FF99C8",
    string = "#A0C4FF",
    type = "#FDFFB6",
    var = "#FFC6FF",
    number = "#9BF6FF",
    boolean = "#FFADAD",
    comment = "#7D7987",
    operator = "#FF99C8",
    constant = "#CAFFBF",
    param = "#E8D5F0",
    delimiter = "#9399B3",
    match_paren = "#FFD166",
    match_bg = "#352033",
    border = "#A0C4FF",
    title = "#FF99C8",
    pmenu_sel = "#FF99C8",
    pmenu_sel_fg = "#30081C",
    diag_err = "#FFADAD",
    diag_warn = "#FDFFB6",
    diag_info = "#9BF6FF",
    diag_hint = "#CAFFBF",
  },
  sunset = {
    keyword = "#BE95C4",
    function_ = "#F72585",
    string = "#4CC9F0",
    type = "#F8961E",
    var = "#F77FBE",
    number = "#4895EF",
    boolean = "#F3722C",
    comment = "#6C6374",
    operator = "#B5179E",
    constant = "#F9C74F",
    param = "#E0AAFF",
    delimiter = "#9399B3",
    match_paren = "#F8961E",
    match_bg = "#361D2B",
    border = "#4CC9F0",
    title = "#F72585",
    pmenu_sel = "#4CC9F0",
    pmenu_sel_fg = "#05202E",
    diag_err = "#F72585",
    diag_warn = "#F9C74F",
    diag_info = "#4895EF",
    diag_hint = "#4CC9F0",
  },
  honeydew = {
    keyword = "#B794F4",
    function_ = "#F687B3",
    string = "#9AE6B4",
    type = "#FBD38D",
    var = "#FEB2B2",
    number = "#90CDF4",
    boolean = "#FC8181",
    comment = "#7C788A",
    operator = "#E9D8FD",
    constant = "#FEFCBF",
    param = "#CBD5E0",
    delimiter = "#9399B3",
    match_paren = "#F6AD55",
    match_bg = "#332338",
    border = "#9AE6B4",
    title = "#F687B3",
    pmenu_sel = "#9AE6B4",
    pmenu_sel_fg = "#102014",
    diag_err = "#FC8181",
    diag_warn = "#FBD38D",
    diag_info = "#90CDF4",
    diag_hint = "#9AE6B4",
  },
  blackberry = {
    keyword = "#C084FC",
    function_ = "#FB7185",
    string = "#5EEAD4",
    type = "#FCD34D",
    var = "#F472B6",
    number = "#7DD3FC",
    boolean = "#F87171",
    comment = "#786B80",
    operator = "#E879F9",
    constant = "#FDE68A",
    param = "#DDD6FE",
    delimiter = "#9399B3",
    match_paren = "#F59E0B",
    match_bg = "#351D2E",
    border = "#C084FC",
    title = "#FB7185",
    pmenu_sel = "#5EEAD4",
    pmenu_sel_fg = "#052924",
    diag_err = "#F87171",
    diag_warn = "#FCD34D",
    diag_info = "#7DD3FC",
    diag_hint = "#5EEAD4",
  },
  alpine = {
    keyword = "#B8C0FF",
    function_ = "#FF99C8",
    string = "#52B788",
    type = "#E0A96D",
    var = "#D8F3DC",
    number = "#74C69D",
    boolean = "#E76F51",
    comment = "#7B746D",
    operator = "#B7E4C7",
    constant = "#FFE8D6",
    param = "#E9ECEF",
    delimiter = "#9399B3",
    match_paren = "#D4A373",
    match_bg = "#302824",
    border = "#52B788",
    title = "#FF99C8",
    pmenu_sel = "#52B788",
    pmenu_sel_fg = "#0B261A",
    diag_err = "#E76F51",
    diag_warn = "#E0A96D",
    diag_info = "#74C69D",
    diag_hint = "#52B788",
  },
  cottoncandy = {
    keyword = "#CDB4DB",
    function_ = "#FFC6FF",
    string = "#BDE0FE",
    type = "#FDFFB6",
    var = "#FFDFD3",
    number = "#A2D2FF",
    boolean = "#FFB5A7",
    comment = "#7D798C",
    operator = "#E8AEFF",
    constant = "#FEFCBF",
    param = "#F8EDEB",
    delimiter = "#9399B3",
    match_paren = "#F4A261",
    match_bg = "#342436",
    border = "#FFC6FF",
    title = "#FFC6FF",
    pmenu_sel = "#BDE0FE",
    pmenu_sel_fg = "#0A2033",
    diag_err = "#FFB5A7",
    diag_warn = "#FDFFB6",
    diag_info = "#A2D2FF",
    diag_hint = "#BDE0FE",
  },
  bubblebobble = {
    keyword = "#D4A5FF",
    function_ = "#FF5D8F",
    string = "#57CC99",
    type = "#FFD166",
    var = "#FFB4D6",
    number = "#38A3A5",
    boolean = "#E63946",
    comment = "#786B7C",
    operator = "#FF85A1",
    constant = "#FFE5D9",
    param = "#E8E8E4",
    delimiter = "#9399B3",
    match_paren = "#F48C06",
    match_bg = "#361A2B",
    border = "#57CC99",
    title = "#FF5D8F",
    pmenu_sel = "#57CC99",
    pmenu_sel_fg = "#08261C",
    diag_err = "#E63946",
    diag_warn = "#FFD166",
    diag_info = "#38A3A5",
    diag_hint = "#57CC99",
  },
}

function M.get_highlights(name, colors)
  local c = M.palettes[name] or M.palettes.harmony

  return {
    -- 🧱 Base UI & Janelas Flutuantes
    NormalFloat = { fg = c.border, bg = "NONE" },
    FloatBorder = { fg = c.border, bg = "NONE" },
    FloatTitle = { fg = c.title, bg = "NONE", bold = true },
    DexHoverNormal = { fg = c.string, bg = "#292628" },
    Transparent = { bg = "NONE" },
    CursorLineNr = { fg = c.operator, bold = true },

    -- 🎯 Parênteses e Delimitadores
    Delimiter = { fg = c.delimiter },
    MatchParen = { fg = c.match_paren, bg = c.match_bg, bold = true },

    -- 🔲 Janela de autocomplete/documentação (nvim-cmp)
    Pmenu = { fg = c.constant, bg = "NONE" },
    PmenuSel = { fg = c.pmenu_sel_fg, bg = c.pmenu_sel, bold = true },
    PmenuThumb = { bg = c.function_ },
    CmpItemAbbr = { fg = c.constant },
    CmpItemAbbrMatch = { fg = c.function_, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.function_, italic = true },
    CmpItemMenu = { fg = c.border, italic = true },

    -- 🧠 Tipos genéricos e por ícone (cmp)
    CmpItemKind = { fg = c.border, bold = true },
    CmpItemKindText = { fg = c.constant },
    CmpItemKindMethod = { fg = c.function_ },
    CmpItemKindFunction = { fg = c.function_ },
    CmpItemKindConstructor = { fg = c.function_ },
    CmpItemKindField = { fg = c.var },
    CmpItemKindVariable = { fg = c.var },
    CmpItemKindClass = { fg = c.type },
    CmpItemKindInterface = { fg = c.type },
    CmpItemKindModule = { fg = c.border },
    CmpItemKindProperty = { fg = c.var },
    CmpItemKindUnit = { fg = c.constant },
    CmpItemKindValue = { fg = c.number },
    CmpItemKindEnum = { fg = c.type },
    CmpItemKindKeyword = { fg = c.keyword },
    CmpItemKindSnippet = { fg = c.string },
    CmpItemKindColor = { fg = c.var },
    CmpItemKindFile = { fg = c.border },
    CmpItemKindReference = { fg = c.border },
    CmpItemKindFolder = { fg = c.border },
    CmpItemKindEnumMember = { fg = c.type },
    CmpItemKindConstant = { fg = c.constant },
    CmpItemKindStruct = { fg = c.type },
    CmpItemKindEvent = { fg = c.boolean },
    CmpItemKindOperator = { fg = c.operator },
    CmpItemKindTypeParameter = { fg = c.type },
    CmpItemKindCopilot = { fg = c.title },
    CmpItemKindAI = { fg = c.keyword, italic = true },

    -- 🔠 Sintaxe Base Unificada
    Comment = { fg = c.comment, italic = true },
    String = { fg = c.string },
    Function = { fg = c.function_, bold = true },
    Keyword = { fg = c.keyword, bold = true, italic = true },
    Type = { fg = c.type },
    Identifier = { fg = c.var },
    Constant = { fg = c.constant },
    Statement = { fg = c.keyword },
    Operator = { fg = c.operator },
    Number = { fg = c.number },
    Boolean = { fg = c.boolean, bold = true },
    Title = { fg = c.border, bold = true },
    Special = { fg = c.border },
    Directory = { fg = c.border },

    -- 🧠 Treesitter Completo & Específico
    ["@function"] = { fg = c.function_, bold = true },
    ["@function.builtin"] = { fg = c.function_ },
    ["@function.macro"] = { fg = c.function_ },
    ["@keyword"] = { fg = c.keyword, italic = true },
    ["@keyword.function"] = { fg = c.keyword, bold = true, italic = true },
    ["@keyword.return"] = { fg = c.keyword, bold = true, italic = true },
    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type },
    ["@constant"] = { fg = c.constant },
    ["@constant.builtin"] = { fg = c.constant },
    ["@variable"] = { fg = c.var },
    ["@variable.builtin"] = { fg = c.title },
    ["@variable.parameter"] = { fg = c.param },
    ["@parameter"] = { fg = c.param },
    ["@field"] = { fg = c.var },
    ["@property"] = { fg = c.var },
    ["@string"] = { fg = c.string },
    ["@string.escape"] = { fg = c.border },
    ["@comment"] = { fg = c.comment, italic = true },
    ["@boolean"] = { fg = c.boolean, bold = true },
    ["@number"] = { fg = c.number },
    ["@operator"] = { fg = c.operator },
    ["@punctuation.bracket"] = { fg = c.delimiter },
    ["@punctuation.delimiter"] = { fg = c.delimiter },
    ["@punctuation.special"] = { fg = c.delimiter },

    -- ⚡ LSP Semantic Tokens
    ["@lsp.type.function"] = { fg = c.function_ },
    ["@lsp.type.method"] = { fg = c.function_ },
    ["@lsp.type.variable"] = { fg = c.var },
    ["@lsp.type.parameter"] = { fg = c.param },
    ["@lsp.type.property"] = { fg = c.var },
    ["@lsp.type.type"] = { fg = c.type },
    ["@lsp.type.class"] = { fg = c.type },
    ["@lsp.type.interface"] = { fg = c.type },
    ["@lsp.type.enum"] = { fg = c.type },
    ["@lsp.type.enumMember"] = { fg = c.type },
    ["@lsp.type.keyword"] = { fg = c.keyword },
    ["@lsp.type.comment"] = { fg = c.comment, italic = true },
    ["@lsp.type.string"] = { fg = c.string },
    ["@lsp.type.number"] = { fg = c.number },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = c.title },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = c.function_ },

    -- 💡 Diagnostics
    DiagnosticUnderlineError = { sp = c.diag_err, underdouble = true, italic = true },
    DiagnosticUnderlineWarn = { sp = c.diag_warn, undercurl = true, italic = true },
    DiagnosticUnderlineInfo = { sp = c.diag_info, undercurl = true, italic = true },
    DiagnosticUnderlineHint = { sp = c.diag_hint, undercurl = true },

    -- ⛓️ StatusLine
    StatusLine = { fg = "#ffd1ea", bg = "#1a0e17" },
    StatusLineNC = { fg = "#cfa5b6", bg = "#1a0e17" },

    -- ✨ Outros / Custom Tags
    Hack = { fg = "#f79e45", bg = "NONE", bold = true },
    Hint = { fg = "#cce6ff", bg = "NONE", italic = true },
    Warn = { fg = "#f5e36c", bg = "NONE", bold = true },
    Fix = { fg = "#ff4f88", bg = "NONE", bold = true },
  }
end

function M.apply(name)
  local theme_name = name or "harmony"
  vim.g.dex_theme = theme_name

  -- Aplica a base do catppuccin
  vim.cmd("colorscheme catppuccin")

  -- Aplica instantaneamente os highlights da paleta selecionada
  local highlights = M.get_highlights(theme_name)
  for group, hl in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end

  vim.g.colors_name = "dex-" .. theme_name
end

return M
