return {
  {
    "catppuccin-nvim/nvim",
    name = "catppuccin-nvim",
    lazy = false,
    priority = 1000,
    main = "catppuccin",
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
    opts = {
      transparent_background = true,
      term_colors = true,
      integrations = {
        aerial = true,
        alpha = true,
        cmp = true,
        dashboard = true,
        flash = true,
        fzf = true,
        grug_far = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        snacks = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },

      custom_highlights = function(colors)
        return {
          NormalFloat = { fg = "#a3c8f1", bg = "NONE" },
          FloatBorder = { fg = "#9dcff9", bg = "NONE" },
          FloatTitle = { fg = "#ff8ebd", bg = "NONE", style = { "bold" } },
          CmpHoverNormal = { fg = "#93E1D4", bg = "#292628" },
          Transparent = { bg = "NONE" },
          CursorLineNr = { fg = "#f86ea7", style = { "bold" } },
          Pmenu = { fg = "#ff8ebd", bg = "NONE" },
          PmenuSel = { fg = "#9dcff9", bg = "NONE" },
          PmenuThumb = { bg = "#ff8ebd" },
          CmpItemAbbr = { fg = "#ffd5ec" },
          CmpItemAbbrMatch = { fg = "#ffb4d4", style = { "bold" } },
          CmpItemAbbrMatchFuzzy = { fg = "#ffb4d4", style = { "italic" } },
          CmpItemMenu = { fg = "#ff8ebd", style = { "italic" } },
          CmpItemKind = { fg = "#9dcff9", style = { "bold" } },
          CmpItemKindText = { fg = "#ffd5ec" },
          CmpItemKindMethod = { fg = "#ff70a3" },
          CmpItemKindFunction = { fg = "#ff70a3" },
          CmpItemKindConstructor = { fg = "#ff70a3" },
          CmpItemKindField = { fg = "#fba6cd" },
          CmpItemKindVariable = { fg = "#fba6cd" },
          CmpItemKindClass = { fg = "#ffc2dc" },
          CmpItemKindInterface = { fg = "#ffc2dc" },
          CmpItemKindModule = { fg = "#addbff" },
          CmpItemKindProperty = { fg = "#fba6cd" },
          CmpItemKindUnit = { fg = "#ffaad3" },
          CmpItemKindValue = { fg = "#ff85b9" },
          CmpItemKindEnum = { fg = "#ff99c3" },
          CmpItemKindKeyword = { fg = "#ffaad3" },
          CmpItemKindSnippet = { fg = "#f0a5cb" },
          CmpItemKindColor = { fg = "#f0a5cb" },
          CmpItemKindFile = { fg = "#a3c8f1" },
          CmpItemKindReference = { fg = "#9dcff9" },
          CmpItemKindFolder = { fg = "#a3c8f1" },
          CmpItemKindEnumMember = { fg = "#ff99c3" },
          CmpItemKindConstant = { fg = "#ffbedd" },
          CmpItemKindStruct = { fg = "#ffc2dc" },
          CmpItemKindEvent = { fg = "#ff85b9" },
          CmpItemKindOperator = { fg = "#f86ea7" },
          CmpItemKindTypeParameter = { fg = "#ffc2dc" },
          CmpItemKindCopilot = { fg = "#ff8ebd" },
          CmpItemKindAI = { fg = "#f0a5cb", style = { "italic" } },
          Comment = { fg = "#f0a5cb", style = { "italic" } },
          String = { fg = "#ffb6d9" },
          Function = { fg = "#ff70a3", style = { "bold" } },
          Keyword = { fg = "#ffaad3", style = { "bold" } },
          Type = { fg = "#ffc2dc" },
          Identifier = { fg = "#fba6cd" },
          Constant = { fg = "#ffbedd" },
          Statement = { fg = "#ff99c3" },
          Operator = { fg = "#f86ea7" },
          Number = { fg = "#ff85b9" },
          Boolean = { fg = "#ff78ae" },
          Title = { fg = "#9dcff9", style = { "bold" } },
          Special = { fg = "#addbff" },
          Directory = { fg = "#a3c8f1" },
          ["@function"] = { fg = "#FF70A2" },
          ["@keyword"] = { fg = "#CAA5F7", style = { "italic" } },
          ["@type"] = { fg = "#FAB286" },
          ["@constant"] = { fg = "#ffbedd" },
          ["@variable"] = { fg = "#fba6cd" },
          ["@string"] = { fg = "#93E1D4" },
          ["@comment"] = { fg = "#f0a5cb", style = { "italic" } },
          ["@boolean"] = { fg = "#f0a5cb" },
          ["@number"] = { fg = "#ff78ae" },
          ["@parameter"] = { fg = "#dd95b8" },
          ["@field"] = { fg = "#fba6cd" },
          DiagnosticUnderlineError = { sp = "#ff4f88", style = { "underdouble", "italic" } },
          DiagnosticUnderlineWarn = { sp = "#ffb4d4", style = { "undercurl", "italic" } },
          DiagnosticUnderlineInfo = { sp = "#a3c8f1", style = { "undercurl", "italic" } },
          DiagnosticUnderlineHint = { sp = "#cce6ff", style = { "undercurl" } },
          StatusLine = { fg = "#ffd1ea", bg = "#1a0e17" },
          StatusLineNC = { fg = "#cfa5b6", bg = "#1a0e17" },
          Hack = { fg = "#f79e45", bg = "NONE", style = { "bold" } },
          Hint = { fg = "#cce6ff", bg = "NONE", style = { "italic" } },
          Warn = { fg = "#f5e36c", bg = "NONE", style = { "bold" } },
          Fix = { fg = "#ff4f88", bg = "NONE", style = { "bold" } },
        }
      end,
    },
  },

  {
    "rose-pine/neovim",
    name = "rose-pine",
    opts = {
      variant = "moon",
      styles = { transparency = true, italic = true, bold = true },
    },
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-nvim",
    },
  },
}
