-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Monitor Setup

-- name: "Default"

-- -----------------------------------------------------

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@60",
    position = "auto",
    scale    = 1,
})
